### ISSUE TITLE
Loci dependency

### ISSUE THREAD

**Issue by justinband** [phac-nml/wade-old#11]
Loci are read from a list.csv file in a specific directory.

In some cases user specified locus (from the main dashboard) will be matched to the same locus in list.csv to check if it exists. Any processing done after will then only be run on the user specified locus if it exists in list.csv, or otherwise on no loci which provides no output.

Again, similar to #9 we have some sort of reliance/dependency in which we need to access data for different things in various locations.

**Comment by TheZetner** [comment]
list.csv files included in the wade-data repository.
