### ISSUE TITLE
Data and File Structure reliance

### ISSUE THREAD

**Issue by justinband** [phac-nml/wade-old#9]
Currently
---
Lots of reliance on directory structures to get data. We don't want this data to exist in the wade package or the docker image.

Some options
---
- Access external DB through Shiny app (https://shiny.rstudio.com/articles/overview.html)
  
  - Can a user specify the DB to look at?

- Access external DB through Docker container

**Comment by TheZetner** [comment]
Added wade-data repository as submodule to maintain the directory structure and allow easy updating and tracking of databases
